server:
  port: 9090
  contextPath: /home

spring:
  application:
    name: vintago

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults:
            false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost/vintagoreal
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver