export const VIEW_TASK_LIST = 'VIEW_TASK_LIST';

export const VIEW_BALANCE_LIST = 'VIEW_BALANCE_LIST';
export const EXECUTE_TRANSFER = 'EXECUTE_TRANSFER';

//--------------------------

export const VIEW_CATEGORIA_LIST = 'VIEW_CATEGORIA_LIST';
export const VIEW_SUBCATEGORIA_LIST = 'VIEW_SUBCATEGORIA_LIST';
export const SAVE_SUBCATEGORIA = 'SAVE_SUBCATEGORIA';
